language: ruby
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
    - bundle exec db:migrate RAILS_ENV=test
    - bundle exec rspec
